### ISSUE TITLE
devolpment?

### ISSUE THREAD

**Issue by DamnUi** [Aurelain/Exo#7]
been about 6 - 7 years since you last touched this, do you have any plans on continuing it?

**Comment by Aurelain** [comment]
I think it's time I admit to myself that I will not be developing _Exo_ anymore.
This [related thread](https://github.com/Aurelain/Exo/issues/2) should provide you with some more insights.

I see the last comment in that thread was 4 years ago. Since then:
- IE became less-and-less supported
- Maybe [RobotJS](https://github.com/octalmage/robotjs) became more mature?

**Comment by joedf** [comment]
You could also give this a try. Although it was mostly an April Fool's joke, it's quite functional!
https://github.com/Lexikos/AutoHotkey-jk

**Comment by DamnUi** [comment]
Thank you! i appreciate it

**Comment by sancarn** [comment]
@Aurelain You might want to archive the project to demonstrate that you won't be maintaining it 😊 

All, depending what you want to do, there are some existing projects which you might find useful:

* [node-global-key-listener](https://github.com/LaunchMenu/node-global-key-listener) Allows capturing of hotkeys etc. via NodeJS. Uses hooks like AHK and has built in handling for stuff like Windows key. Also is cross platform.
* [robotjs](https://github.com/octalmage/robotjs) unfortuantely not well maintained but existing and sometime works.
* [OSIntegrationServer](https://github.com/LaunchMenu/LaunchMenu/issues/128) - This is a work in progress project which aims to provide all the essentials missing from NodeJS for OS integration without the need for node-gyp. Currently it's very bare but the hope is to expand into operating system agnostic implementations for:
    * Support to capture keyboard shortcuts
    * Support to listen for general key events
    * Support to SendKeys
    * Support to insert text at cursor
    * Support to host a COM/AppleEvents Server
    * Support to interact with COM/AppleEvents Servers.
    * Write to/Read from clipboard history
    * Extracting window information (especially active window)
    * Task bar / dock manipulation
    * Windows Explorer / Finder integration
    * Audio Integration for sound boards

This is a long term project, and we are still in the research stage but we're thinking of building the Windows server in Rust. So if there are any hobbyist rust devs out there get in touch, otherwise it's perhaps one to watch 😊

**Comment by Aurelain** [comment]
Thanks for the pointers.
I added a [notice](https://github.com/Aurelain/Exo#archived) about the project being archived and also provided some links to alternative paths mentioned in this thread.

As for OSIntegrationServer, any direction that gets rid of that cursed node-gyp is welcomed :).
